### ISSUE TITLE
Missing things

### ISSUE THREAD

**Issue by ank1traj** [GauravBurande/assignment_calender_emulation_webapp#1]
It was a pleasant one @GauravBurande. But there are too many constraints and restrictions missing from the web app. You can work on that and it will become an excellent app. If you need any help you can always contact me.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/32160084/217306800-a356df7a-fc0c-4482-b40f-63b08ab036ac.png">

**Comment by GauravBurande** [comment]
Sure, I'll work on that👍
